### PR TITLE
Rough outline of home page and basic site styles

### PR DESCRIPTION
**Pull request by kmcgillivray**
Hey @chrisjaure, we've done a bit of work on the site, mainly on the text content and organization of the home page and some basic site styles for the navigation, typography, etc. It's in a very rough state right now, and we have a lot more that we want to do and other ideas that aren't reflected in this yet, but I wanted to send this over to you sooner rather than later.

### CODE REVIEW

**Comment by chrisjaure** [comment]
@kmcgillivray This is a great start! I look forward to seeing it polished up :)

Thanks for sharing. Let me know if you need anything.

**Comment by chrisjaure** [comment]
@kmcgillivray Would it be ok if I put a hard deadline on this for the end of July? I need to make sure the site it ready to go by probably the end of August.

**Comment by kmcgillivray** [comment]
@chrisjaure Yes, absolutely. That will help us move forward and stay organized. I'll have more to show you soon.

**Comment by chrisjaure** [comment]
@kmcgillivray Gentle reminder that the deadline is approaching :)

**Comment by chrisjaure** [comment]
Oh wow, just checked out your updates from a three weeks ago. That animation is pretty slick!

**Comment by kmcgillivray** [comment]
@chrisjaure Thanks for the reminder! We're in good shape I think, lots of tiny details to clean up and a couple big things left but I think we're on track. Glad you like the animation! It's a rough draft right now and we have a few more "slides" we want to add, but glad you like the idea.

Any word on where it will be held this year? Any feedback on content/organization of the home page?

**Comment by chrisjaure** [comment]
@kmcgillivray The date an location this year is November 7 at NTWC (same place as last year).

The content looks pretty good so far.

**Comment by chrisjaure** [comment]
Hi @kmcgillivray. Time's up! :)

Is the design done?

**Comment by kmcgillivray** [comment]
@chrisjaure Yes! There are a couple small details I was going to clean up this weekend, but everything should be set to go. Let me know if you want to meet up on Slack sometime to talk through it/give feedback/talk about what else might need to be done that we missed.

**Comment by chrisjaure** [comment]
@kmcgillivray For sure. Feel free to ping me on Slack whenever is good for you.

**Pull request merged**
